"""Alembic environment (M0).

The URL comes from application settings so there is one source of truth and no
credentials in `alembic.ini`. Every module's models are imported below: a model
missing from this list is invisible to `--autogenerate`.
"""
from __future__ import annotations

from logging.config import fileConfig

from sqlalchemy import engine_from_config, pool

from alembic import context

# Model imports, one line per module that owns tables. Add to this list in the
# module that introduces the table (M1 identity, M2 catalogue, and so on).
from app.audit import models as audit_models  # noqa: F401
from app.core.config import get_settings
from app.core.db import Base

config = context.config
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

config.set_main_option("sqlalchemy.url", get_settings().database_url)
target_metadata = Base.metadata


POSTGIS_INTERNAL_TABLES = frozenset({"spatial_ref_sys", "geography_columns", "geometry_columns"})


def _include_object(
    obj: object, name: str | None, type_: str, reflected: bool, compare_to: object
) -> bool:
    """Keep PostGIS's own bookkeeping out of autogenerated migrations."""
    return not (type_ == "table" and name in POSTGIS_INTERNAL_TABLES)


def run_migrations_offline() -> None:
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        include_object=_include_object,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
            include_object=_include_object,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
